{
	"Service": "/MDKSample1/Services/MDKSampleAPP.service",
	"DefiningRequests": [{
		"Name": "SalesOrderHeaders",
		"Query": "SalesOrderHeaders"
	}, {
		"Name": "SalesOrderItems",
		"Query": "SalesOrderItems"
	}],
	"_Type": "Action.Type.OfflineOData.Initialize",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Downloading...",
	"ActionResult": {
		"_Name": "init"
	},
	"OnSuccess": "/MDKSample1/Actions/Service/InitializeOfflineSuccessMessage.action",
	"OnFailure": "/MDKSample1/Actions/Service/InitializeOfflineFailureMessage.action"
}