{
	"OnFailure": "/MDKSample1/Actions/ValFalilurFCNAME.action",
	"OnInvalidLog": {
		"Level": "Warn",
		"Message": "---> Falsche Eingabe ---"
	},
	"RequiredFields": [
		"FCmyName"
	],
	"ValidationRule": "/MDKSample1/Rules/checkInput.js",
	"_Type": "Action.Type.CheckRequiredFields"
}