{
	"Animated": true,
	"Duration": 5,
	"Message": "Bittte Eingaben prüfen",
	"OnFailureLog": {
		"Level": "Error",
		"Message": "Eingabe im Input Feld flasch"
	},
	"OnSuccessLog": {
		"Level": "Info",
		"Message": "Gut gemacht "
	},
	"_Type": "Action.Type.BannerMessage"
}