{
	"OnFailure": "/MDKSample1/Rules/UpdateRequiredFailed.js",
	"OnInvalidLog": {
		"Level": "Warn",
		"Message": "---> Falsche Eingabe ---"
	},
	"OnSuccess": "/MDKSample1/Actions/SucStdMessageAct.action",
	"RequiredFields": [
		"FCmyName"
	],
	"_Type": "Action.Type.CheckRequiredFields"
}